In [2]:
import numpy as np
import pandas as pd

In [3]:
# Arrays
# it allows only 1 type of values

a1=np.array([2,5,6,9,8,25])

In [25]:
a1

array([ 2,  5,  6,  9,  8, 25])

In [27]:
a1[2:5:2]

array([6, 8])

In [5]:
a1[0]

2

In [10]:
type(a1)

numpy.ndarray

In [11]:
a1[0]

2

In [6]:
a2=np.array([[45,23,14],[78,5,63]])

In [7]:
a2

array([[45, 23, 14],
       [78,  5, 63]])

In [9]:
a2[0,1]

23

In [9]:
a2[:,2]

array([14, 63])

In [10]:
a2.ndim

2

In [17]:
a1.ndim

1

In [18]:
a1

array([ 2,  5,  6,  9,  8, 25])

In [10]:
a3=np.array([[55,22,73],
[46,70,80],
[47,50,24]
])

In [24]:
a3[1:,1:]

array([[70, 80],
       [50, 48]])

In [23]:
a3.ndim

2

In [19]:
a1[-1]

25

In [20]:
a1[2:5]

array([6, 9, 8])

In [23]:
a1[2:]

array([ 6,  9,  8, 25])

In [24]:
a1[:2]

array([2, 5])

In [ ]:
a[start:end:step]

In [26]:
a1[2:6:2]

array([6, 8])

In [27]:
a1[::2]

array([2, 6, 8])

In [28]:
a1

array([ 2,  5,  6,  9,  8, 25])

In [29]:
a1[:2]

array([2, 5])

In [30]:
a1.dtype

dtype('int32')

In [31]:
a3=np.array(['A','B','C'])

In [32]:
a3.dtype

dtype('<U1')

In [42]:
a4=np.array([3,4,6,120],dtype='f')

In [43]:
a4

array([  3.,   4.,   6., 120.], dtype=float32)

In [44]:
a4.dtype

dtype('float32')

In [45]:
a4.astype(int)

array([  3,   4,   6, 120])

In [46]:
a4.shape

(4,)

In [47]:
a2.shape

(2, 3)

In [49]:
ar1=np.array([4,12,54])
ar2=np.array([54,90,29])

In [50]:
ar3=np.concatenate((ar1,ar2))

In [51]:
ar3

array([ 4, 12, 54, 54, 90, 29])

In [53]:
ar4=np.concatenate((ar1,ar2),axis=0)

In [54]:
ar4

array([ 4, 12, 54, 54, 90, 29])

In [28]:
ar5=np.array([[23,34],[34,34]])
ar6=np.array([[123,134],[134,134]])

In [57]:
ar7=np.concatenate((ar5,ar6),axis=1)

In [58]:
ar7

array([[ 23,  34, 123, 134],
       [ 34,  34, 134, 134]])

In [59]:
np.hstack((ar5,ar6))

array([[ 23,  34, 123, 134],
       [ 34,  34, 134, 134]])

In [31]:
ar6=np.vstack((ar5,ar6))

In [32]:
ar6

array([[ 23,  34],
       [ 34,  34],
       [123, 134],
       [134, 134]])

In [34]:
np.where(ar6==23)

(array([0], dtype=int64), array([0], dtype=int64))

In [63]:
ar5

array([[23, 34],
       [34, 34]])

In [64]:
np.mean(a1)

9.166666666666666

In [65]:
np.sqrt(a1)

array([1.41421356, 2.23606798, 2.44948974, 3.        , 2.82842712,
       5.        ])

In [66]:
np.median(a1)

7.0

In [68]:
np.median(a1)

7.0

# 

In [36]:
np.where(a1==25,)

(array([5], dtype=int64),)

In [37]:
a1=np.array([2,5,6,9,8,25,5])

In [39]:
np.where(a1==5,7,a1)

array([ 2,  7,  6,  9,  8, 25,  7])